# Generated by Django 3.2.9 on 2021-12-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_order_id', models.CharField(max_length=30, unique=True)),
                ('txn_oder_amnt', models.DecimalField(decimal_places=4, max_digits=12)),
                ('txn_pmnt_id', models.CharField(max_length=30, unique=True)),
                ('txn_signature', models.CharField(max_length=256)),
            ],
        ),
    ]
